name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo-step
        run: echo "Hello World!"
      - name: list-step
        run: ls -l && ls -l ..
      - name: pwd-step
        run: pwd
